"""``POST /api/curator/query`` -- isolated scope-bound Q&A (Stage L).

The Curator endpoint lets the operator ask a question scoped to either
a Group (every root session in that group) or a single session+chain
(the picked session and every ancestor back to the root). The answer
is generated by a *separate* loom session running in its own per-query
cwd, so the chat session that prompted the lookup is never
contaminated.

Streaming uses Server-Sent Events so the SPA can render text deltas
as the underlying agent produces them. Each AcpChunk is serialized as
``event: <chunk_type>`` / ``data: <json>``; the stream ends with
``event: end_turn`` so the client knows to stop reading.

Errors raised by :class:`CuratorRunner` map as follows:

* :class:`CuratorScopeError` -- 404 (the requested group/session is
  missing or unsupported);
* :class:`CuratorContextError` -- 503 when the agent backend or
  required context mode is disabled.

A scoped 400/422 from Pydantic is the normal validation path so we do
not catch :class:`ValueError` ourselves.
"""

from __future__ import annotations

import json
import logging
from collections.abc import AsyncIterator
from typing import Annotated, Literal, cast
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Request, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from stratoclave_atelier.curator import (
    CuratorContextError,
    CuratorRunner,
    CuratorScopeError,
)

logger = logging.getLogger(__name__)


router = APIRouter(prefix="/api/curator", tags=["curator"])


def _get_curator_runner(request: Request) -> CuratorRunner:
    runner = getattr(request.app.state, "curator_runner", None)
    if runner is None:  # pragma: no cover -- developer error if hit
        raise RuntimeError(
            "CuratorRunner is not configured on app.state.curator_runner; "
            "build the app via create_app() so the lifespan can attach one"
        )
    return cast(CuratorRunner, runner)


CuratorRunnerDep = Annotated[CuratorRunner, Depends(_get_curator_runner)]


class CuratorQueryRequest(BaseModel):
    """Body of ``POST /api/curator/query``.

    ``scope_kind`` selects between a Group (every root session in the
    group) and a single session (target + ancestor chain). ``context_mode``
    picks distilled memory vs raw events; the latter is the safe default
    when distill is disabled.
    """

    scope_kind: Literal["group", "session"]
    scope_id: UUID
    context_mode: Literal["distill", "raw"] = "raw"
    question: str = Field(..., min_length=1, max_length=8_000)
    backend: str | None = Field(
        default=None,
        description=(
            "Optional loom backend override. When unset, the server default "
            "(``ATELIER_AGENT_BACKEND``) is used."
        ),
    )


def _format_chunk(chunk_type: str, content: dict[str, object]) -> bytes:
    """Render an AcpChunk as a single SSE frame.

    The frame uses ``event: <chunk_type>`` so the client can dispatch on
    type via ``EventSource.addEventListener``. The data payload is JSON
    so multi-line text deltas survive the SSE single-line constraint.
    """

    body = json.dumps(content, ensure_ascii=False, separators=(",", ":"))
    return f"event: {chunk_type}\ndata: {body}\n\n".encode()


@router.post("/query")
async def query_curator(
    body: CuratorQueryRequest,
    runner: CuratorRunnerDep,
) -> StreamingResponse:
    """Stream the Curator's answer as SSE chunks.

    The handler resolves the scope and builds the context block before
    returning the response so client-visible 4xx/5xx errors fire as
    JSON, not as a half-open SSE stream. Streaming only starts once we
    have a live loom session.
    """

    try:
        stream = await runner.curate(
            scope_kind=body.scope_kind,
            scope_id=body.scope_id,
            context_mode=body.context_mode,
            question=body.question,
            backend=body.backend,
        )
    except CuratorScopeError as exc:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(exc)) from exc
    except CuratorContextError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail=str(exc)
        ) from exc

    async def emit() -> AsyncIterator[bytes]:
        try:
            async for chunk in stream:
                yield _format_chunk(chunk.chunk_type, dict(chunk.content))
        except Exception as exc:  # pragma: no cover -- backend failure path
            logger.exception("curator stream failed")
            yield _format_chunk("error", {"error": str(exc), "type": exc.__class__.__name__})
        finally:
            yield _format_chunk("end_turn", {})

    return StreamingResponse(
        emit(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
            "Connection": "keep-alive",
        },
    )


__all__ = ["router"]
